server:
  port: 9000
spring:
  application:
    name: cards
  datasource:
    url: jdbc:h2:mem:cardsdb
    username: admin
    password: admin
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
management:
  endpoints:
    web:
      exposure:
        include: '*'